### PR TITLE
Removing spring cloud components

### PR DESCRIPTION
**Pull request by jgkong**
Resolves sdevopsadm/roadmap#3

### CODE REVIEW

**Comment by gracehyunjuyang** [comment]
Please resolve the conflict.

**Comment by sdevopsadm** [comment]
Bluemix [toolchain](https://console.bluemix.net/devops/toolchains/85559b6d-3b47-4c86-88b5-a3688e68285b "PoC2_petclinic_microservice_jgkong"): [Delivery Pipeline](https://console.bluemix.net/devops/pipelines/5e65a470-ac27-4ff4-9123-1ce97f9f44db "PoC2-api-gateway-jgkong") deployed [spring-petclinic-microservices](https://github.com/sdevopsadm/spring-petclinic-microservices/releases/tag/deploy-ibm-yp-us-south-VDInfraPOC-dev-20170629-041513 "deploy-ibm-yp-us-south-VDInfraPOC-dev-20170629-041513") to [dev](https://console.bluemix.net/apps/a4a4c98c-f00c-41f5-a60c-4751e5da00e0?env_id=ibm:yp:us-south "ibm:yp:us-south:VDInfraPOC:dev"), including commit d4b9fe339b388538e6439ff91af1d7a966516291

**Comment by sdevopsadm** [comment]
Bluemix [toolchain](https://console.bluemix.net/devops/toolchains/85559b6d-3b47-4c86-88b5-a3688e68285b "PoC2_petclinic_microservice_jgkong"): [Delivery Pipeline](https://console.bluemix.net/devops/pipelines/673651ec-45f6-4e57-977b-ac018a92f419 "PoC2-vets-service-jgkong") deployed [spring-petclinic-microservices](https://github.com/sdevopsadm/spring-petclinic-microservices/releases/tag/deploy-ibm-yp-us-south-VDInfraPOC-dev-20170629-042646 "deploy-ibm-yp-us-south-VDInfraPOC-dev-20170629-042646") to [dev](https://console.bluemix.net/apps/076deb48-e8d0-4c56-b906-7cca0e7090da?env_id=ibm:yp:us-south "ibm:yp:us-south:VDInfraPOC:dev"), including commit d4b9fe339b388538e6439ff91af1d7a966516291

**Comment by sdevopsadm** [comment]
Bluemix [toolchain](https://console.bluemix.net/devops/toolchains/85559b6d-3b47-4c86-88b5-a3688e68285b "PoC2_petclinic_microservice_jgkong"): [Delivery Pipeline](https://console.bluemix.net/devops/pipelines/5e65a470-ac27-4ff4-9123-1ce97f9f44db "PoC2-api-gateway-jgkong") deployed [spring-petclinic-microservices](https://github.com/sdevopsadm/spring-petclinic-microservices/releases/tag/deploy-ibm-yp-us-south-VDInfraPOC-qa-20170629-043922 "deploy-ibm-yp-us-south-VDInfraPOC-qa-20170629-043922") to [qa]( "ibm:yp:us-south:VDInfraPOC:qa"), including commit d4b9fe339b388538e6439ff91af1d7a966516291

**Comment by sdevopsadm** [comment]
Bluemix [toolchain](https://console.bluemix.net/devops/toolchains/85559b6d-3b47-4c86-88b5-a3688e68285b "PoC2_petclinic_microservice_jgkong"): [Delivery Pipeline](https://console.bluemix.net/devops/pipelines/673651ec-45f6-4e57-977b-ac018a92f419 "PoC2-vets-service-jgkong") deployed [spring-petclinic-microservices](https://github.com/sdevopsadm/spring-petclinic-microservices/releases/tag/deploy-ibm-yp-us-south-VDInfraPOC-qa-20170629-051215 "deploy-ibm-yp-us-south-VDInfraPOC-qa-20170629-051215") to [qa]( "ibm:yp:us-south:VDInfraPOC:qa"), including commit d4b9fe339b388538e6439ff91af1d7a966516291

**Pull request merged**
